name: Build and Release Archival RPC Playground

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Enable Docker Content Trust (DCT)
      - name: Enable Docker Content Trust
        run: echo "DOCKER_CONTENT_TRUST=1" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t dexterlaboss/archival-rpc-playground:${GITHUB_REF_NAME} .
          docker push dexterlaboss/archival-rpc-playground:${GITHUB_REF_NAME}
